name: Feature Branch

on:
  push:
  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    #Job's steps
    steps:
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
#      - name: Get GitHub App Installation Token
#        id: checkout-app
#        uses: getsentry/action-github-app-token@v1
#        with:
#          app_id: ${{ secrets.CX_WORKFLOW_DISPATCH_APP_ID }}
#          private_key: ${{ secrets.CX_WORKFLOW_DISPATCH_APP_PRIVATE_KEY }}

      - name: Dispatch repository_dispatch event
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_APP_ID}}
          type: repository
          repo: getmelo/githubactions-listener
          ident: client-dispatched # refer to on.repository_dispatch.types.*
          payload: '{}' # json
